export const materias = [
  'Língua Portuguesa',
  'Matemática',
  'Ciências',
  'História',
  'Geografia',
  'Educação Física',
  'Arte',
  'Inglês',
  'Espanhol',
  'Música',
  'Ensino Religioso',
  'Biologia',
  'Química',
  'Física',
  'Literatura',
  'Redação',
  'Geometria',
  'Álgebra',
];
