export const materias = [
  { materia: 'Língua Portuguesa', slug: 'lingua-portuguesa' },
  { materia: 'Matemática', slug: 'matematica' },
  { materia: 'Ciências', slug: 'ciencias' },
  { materia: 'História', slug: 'historia' },
  { materia: 'Geografia', slug: 'geografia' },
  { materia: 'Educação Física', slug: 'educacao-fisica' },
  { materia: 'Arte', slug: 'arte' },
  { materia: 'Inglês', slug: 'ingles' },
  { materia: 'Espanhol', slug: 'espanhol' },
  { materia: 'Música', slug: 'musica' },
  { materia: 'Ensino Religioso', slug: 'estudo-religioso' },
  { materia: 'Biologia', slug: 'biologia' },
  { materia: 'Química', slug: 'quimica' },
  { materia: 'Física', slug: 'fisica' },
  { materia: 'Literatura', slug: 'literatura' },
  { materia: 'Redação', slug: 'redacao' },
  { materia: 'Geometria', slug: 'geometria' },
  { materia: 'Álgebra', slug: 'algebra' },
];
