export const turmas = [
  {
    turma: '1º Ano Do Ensino Fundamental',
    slug: '1-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '2º Ano Do Ensino Fundamental',
    slug: '2-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '3º Ano Do Ensino Fundamental',
    slug: '3-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '4º Ano Do Ensino Fundamental',
    slug: '4-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '5º Ano Do Ensino Fundamental',
    slug: '5-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '6º Ano Do Ensino Fundamental',
    slug: '6-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '7º Ano Do Ensino Fundamental',
    slug: '7-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '8º Ano Do Ensino Fundamental',
    slug: '8-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '9º Ano Do Ensino Fundamental',
    slug: '9-f',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Ciências',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
      'Música',
    ],
  },
  {
    turma: '1º Ano Do Ensino Médio',
    slug: '1-m',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Biologia',
      'Química',
      'Física',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
    ],
  },
  {
    turma: '2º Ano Do Ensino Médio',
    slug: '2-m',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Biologia',
      'Química',
      'Física',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
    ],
  },
  {
    turma: '3º Ano Do Ensino Médio',
    slug: '3-m',
    materias: [
      'Língua Portuguesa',
      'Matemática',
      'Biologia',
      'Química',
      'Física',
      'História',
      'Geografia',
      'Educação Física',
      'Arte',
      'Inglês',
    ],
  },
];
